
// eslint-disable-next-line import/no-mutable-exports
export let vid;
// eslint-disable-next-line import/no-mutable-exports
export let overlay;
// eslint-disable-next-line import/no-mutable-exports
export let overlayCC;
// eslint-disable-next-line import/no-mutable-exports
export let vidWidth;
// eslint-disable-next-line import/no-mutable-exports
export let vidHeight;
// eslint-disable-next-line import/no-mutable-exports
export let isTracking;
// eslint-disable-next-line import/no-mutable-exports
export let previousValues;
// eslint-disable-next-line import/no-mutable-exports
export let analyser;
// eslint-disable-next-line import/no-mutable-exports
export let frequencies;
// eslint-disable-next-line import/no-mutable-exports
export let centerX;
// eslint-disable-next-line import/no-mutable-exports
export let centerY;
// eslint-disable-next-line import/no-mutable-exports
export let centerZ;
// eslint-disable-next-line import/no-mutable-exports
export let emotions;
// eslint-disable-next-line import/no-mutable-exports
export let volume;
// eslint-disable-next-line import/no-mutable-exports
export let dataStack;
// eslint-disable-next-line import/no-mutable-exports,camelcase
export let pre_eyes_center_x;
// eslint-disable-next-line import/no-mutable-exports,camelcase
export let pre_eyes_center_y;
// eslint-disable-next-line import/no-mutable-exports,camelcase
export let body_deg;
// eslint-disable-next-line import/no-mutable-exports,camelcase
export let motion_time;
